/// Flutter icons PasswordIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PasswordIcons
///      fonts:
///       - asset: fonts/PasswordIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PasswordIcons {
  PasswordIcons._();

  static const _kFontFam = 'PasswordIcons';
  static const String? _kFontPkg = null;

  static const IconData hiddenEye =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visibleEye =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
